# General Information
global CLIENT_PORT

# Manage HoneyWalt Configuration
global CMD_CLIENT_DOOR, CMD_CLIENT_DOOR_ADD, CMD_CLIENT_DOOR_CHG, CMD_CLIENT_DOOR_DEL, CMD_CLIENT_DOOR_SHOW
global CMD_CLIENT_CTRL, CMD_CLIENT_CTRL_SET, CMD_CLIENT_CTRL_SHOW
global CMD_CLIENT_DEV, CMD_CLIENT_DEV_ADD, CMD_CLIENT_DEV_CHG, CMD_CLIENT_DEV_DEL, CMD_CLIENT_DEV_SHOW
global CMD_CLIENT_IMG, CMD_CLIENT_IMG_ADD, CMD_CLIENT_IMG_CHG, CMD_CLIENT_IMG_DEL, CMD_CLIENT_IMG_SHOW

# Manage HoneyWalt State
global CMD_CLIENT_VM, CMD_CLIENT_VM_SHELL, CMD_CLIENT_VM_START, CMD_CLIENT_VM_STOP
global CMD_CLIENT_START
global CMD_CLIENT_COMMIT
global CMD_CLIENT_STOP
global CMD_CLIENT_RESTART
global CMD_CLIENT_STATUS



CLIENT_PORT = 9999

CMD_CLIENT_DOOR = 1

CMD_CLIENT_DOOR_ADD = 1
CMD_CLIENT_DOOR_CHG = 2
CMD_CLIENT_DOOR_DEL = 3
CMD_CLIENT_DOOR_SHOW= 4

CMD_CLIENT_CTRL = 2

CMD_CLIENT_CTRL_SET = 1
CMD_CLIENT_CTRL_SHOW= 2

CMD_CLIENT_DEV = 3

CMD_CLIENT_DEV_ADD = 1
CMD_CLIENT_DEV_CHG = 2
CMD_CLIENT_DEV_DEL = 3
CMD_CLIENT_DEV_SHOW= 4

CMD_CLIENT_IMG = 4

CMD_CLIENT_IMG_ADD = 1
CMD_CLIENT_IMG_CHG = 2
CMD_CLIENT_IMG_DEL = 3
CMD_CLIENT_IMG_SHOW= 4

CMD_CLIENT_VM = 5

CMD_CLIENT_VM_SHELL= 1
CMD_CLIENT_VM_START= 2
CMD_CLIENT_VM_STOP = 3

CMD_CLIENT_START  = 6
CMD_CLIENT_COMMIT = 7
CMD_CLIENT_STOP   = 8
CMD_CLIENT_RESTART= 9
CMD_CLIENT_STATUS = 10