global CONTROL_PORT, CMD_VM_PHASE, CMD_VM_WALT_DEVS, CMD_VM_WALT_IPS, CMD_VM_WG_KEYGEN, CMD_VM_WG_DOORS, CMD_VM_WG_UP, CMD_VM_WG_DOWN, CMD_VM_COMMIT, CMD_VM_SHUTDOWN, CMD_VM_LIVE, VM_COMMANDS

CONTROL_PORT = 5555

CMD_VM_PHASE = 1

CMD_VM_WALT_DEVS = 2
CMD_VM_WALT_IPS = 3

CMD_VM_WG_KEYGEN = 4
CMD_VM_WG_DOORS = 5
CMD_VM_WG_UP = 6
CMD_VM_WG_DOWN = 7

CMD_VM_COMMIT = 8
CMD_VM_SHUTDOWN = 9
CMD_VM_LIVE = 10

VM_COMMANDS = {
"CMD_VM_PHASE":CMD_VM_PHASE,
"CMD_VM_WALT_DEVS":CMD_VM_WALT_DEVS,
"CMD_VM_WALT_IPS":CMD_VM_WALT_IPS,
"CMD_VM_WG_KEYGEN":CMD_VM_WG_KEYGEN,
"CMD_VM_WG_DOORS":CMD_VM_WG_DOORS,
"CMD_VM_WG_UP":CMD_VM_WG_UP,
"CMD_VM_WG_DOWN":CMD_VM_WG_DOWN,
"CMD_VM_COMMIT":CMD_VM_COMMIT,
"CMD_VM_SHUTDOWN":CMD_VM_SHUTDOWN,
"CMD_VM_LIVE":CMD_VM_LIVE
}